### ISSUE TITLE
rsvg-convert not processing symbols and crashing

### ISSUE THREAD

**Issue by luedi0** [pjimenezmateo/kindle-wallpaper#18]
I've noticed that rsvg-convert cannot convert special characters such as &
They need to be unescaped in order to prevent the following error:
`Error reading SVG:Error domain 1 code 23 on line 30 column 78 of data: EntityRef: expecting ';'`
parse_ical.py would need to add unescaping to the calendar entries.

**Comment by pjimenezmateo** [comment]
It should be fixed now! :D Thanks for reporting this issue.

**Comment by luedi0** [comment]
Hi, it seems that the unescaping code does not work. Special characters like & stay in the SVG as is. Also your code was only for all day events. not regular events. I couldn't figure out why it wouldn't parse properly

**Comment by pjimenezmateo** [comment]
I just updated the code so that the fix also includes non-all-day events.

I am not sure about the first part of your message "Hi, it seems that the unescaping code does not work. Special characters like & stay in the SVG as is." I have tested it with a few characters [ñ, ', ", <, >, &] and everything seems to work on my side. Can you give me an example of text that does not work on your side so I can look at this further?
