### ISSUE TITLE
Usability in 2020 new path to screensaver hack, screen timeout

### ISSUE THREAD

**Issue by luedi0** [pjimenezmateo/kindle-wallpaper#6]
Hi Pablo and others,
I am using a Kindle 3 (Keyboard) with latest FW 3.4.3.
The Kindle script still works, pulling the done.png from my raspberry pi server and saving it in the screensaver directory (other path: /linkss/screensavers).Currently the cronjob on the kindle is refreshing the screensaver picture but because of the reboot, the screensaver is not visible for a while after the reboot until the screen times out. Do you know how to let it go straight to screensaver after reboot?

**Comment by pjimenezmateo** [comment]
Hi luedi0,

I was not aware that someone was still using this repo, I will try to update to a new weather API then (I hope to get the time to do it).

Regarding your question, does the screensaver refresh just after being pulled? If so it is just a matter of removing the reboot. AFAIK, there was no way to let it go directly to screensaver. It reboots because when I was trying it it did not refresh until reboot.

**Comment by pjimenezmateo** [comment]
Hi again,

my latest commit should fix this, just modify the launch.sh file on your Kindle and let me know. I will keep this open in the meantime.
